### ISSUE TITLE
Results file

### ISSUE THREAD

**Issue by najar-nurav** [manuel-freire/ac2#13]
Hi

I want to obtain the results of the plagiarism test in a csv/xml format for further processing, but the "Results file" option in ac2 is not helping with it (if that is its intended purpose to begin with). Kindly advise if there is an alternate way to obtain the results in this manner.

Thanks

**Comment by manuel-freire** [comment]
Closing old issues - while it is possible to dump distances between submissions in AC, this is not the expected way to use it: distances in their context requires visualizations. You *can* extract the data by modifying `ac-ui/src/main/java/es/ucm/fdi/ac/gui/TestResultsDialog.java` (which displays raw distances); or even better, by outputting distances when running tests (see `ac-core/src/main/java/es/ucm/fdi/ac/Analysis.java`)
