### ISSUE TITLE
How to Build Command-line tool?

### ISSUE THREAD

**Issue by suredie** [manuel-freire/ac2#14]
Thanks for this excellent work.
How to build a command-line tool to run comparisons without any interface?

**Comment by ambientlight** [comment]
if this helps, if you open the repo in VSCode, let the java plugin to kick which will resolve the maven and setup the workspace, you can then right click on something that has `public static void main(String[] args)` defined like [ac-core/src/main/java/es/ucm/fdi/ac/cli/Extractor.java](https://github.com/manuel-freire/ac2/blob/master/ac-core/src/main/java/es/ucm/fdi/ac/cli/Extractor.java) in the navigator, click on `Run Java`, which will run the cli via invocation looking something like:

```
/usr/bin/env /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 @/var/folders/pg/w1qknr0s7tqdf7q63m2h846c0000gn/T/cp_3x3q4gxhhyxxozb9r2t64jcyj.argfile es.ucm.fdi.ac.cli.Extractor
```

but `ac-core` doesn't seem to come with ready-to-use cli from what I can tell... only the ac-ui works out of the box (https://github.com/manuel-freire/ac2/blob/master/ac-ui/src/main/java/es/ucm/fdi/ac/Main.java)

**Comment by manuel-freire** [comment]
You can certainly build a UI into `ac-core` (there used to be one, but AFAIK I was the only user). However, in my experience, it is very rare to get submissions lined up into folders exactly as AC expects them. To build a CLI, just add a main method that builds and launches an `ac-core/src/main/java/es/ucm/fdi/ac/Analysis.java` on some sources with a test - and report the results.
