### ISSUE TITLE
How to run the project??

### ISSUE THREAD

**Issue by priya1996** [manuel-freire/ac2#2]

**Comment by manuel-freire** [comment]
Simplest way is to download the [latest executable jar](https://github.com/manuel-freire/ac2/releases/latest) and run `java -jar path-to-jar/name-of-jar`.

**Comment by priya1996** [comment]
What is the language that has been used in the interface??

**Comment by manuel-freire** [comment]
Fixed bug that was ignoring English and defaulting to Spanish. Please try again with latest version.

**Comment by priya1996** [comment]
Thank you so much!!

**Comment by priya1996** [comment]
Can you please give some sample assignment files that can be used to run the project? Thanks in advance.
