### ISSUE TITLE
Build Error: Some files do not have the expected license

### ISSUE THREAD

**Issue by LuisLlana** [manuel-freire/ac2#25]
I am tring to build it on ubnutu

`$ java -version
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
`

I get this error:

`
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.1:check (check-headers) on project ac: Some files do not have the expected license
`

**Comment by manuel-freire** [comment]
Seems to be solved a few versions ago
