### ISSUE TITLE
Compilation failure: package LogPanel does not exist

### ISSUE THREAD

**Issue by sieste** [manuel-freire/ac2#27]
Any ideas how I might address the following compilation error? -- Thanks, Stefan

mvn clean package

> ....
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] /home/stefan/.local/src/ac2/ac-ui/src/main/java/es/ucm/fdi/ac/Main.java:[51,62] package LogPanel does not exist
> ....
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project ac-ui: Compilation failure
> [ERROR] /home/stefan/.local/src/ac2/ac-ui/src/main/java/es/ucm/fdi/ac/Main.java:[51,62] package LogPanel does not exist
> [ERROR]
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :ac-ui
> 
> 

java -version
> openjdk version "1.8.0_352"
> OpenJDK Runtime Environment (build 1.8.0_352-b08)
> OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)

mvn -version
> Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
> Maven home: /opt/maven
> Java version: 1.8.0_352, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk/jre
> Default locale: en_GB, platform encoding: UTF-8
> OS name: "linux", version: "6.0.11-arch1-1", arch: "amd64", family: "unix"

git log -1
> commit 02b2e42e8c8f7d0d1e232676707773cb1606e363 (HEAD -> master, origin/master, origin/HEAD)
> Author: Manuel Freire <manuel.freire@gmail.com>
> Date:   Fri Feb 18 04:53:04 2022 +0100
> 
>     cleanup to remove a few additional warnings

**Comment by sieste** [comment]
PS: I also get an error about LogPanel when trying to run the latest release:

java -jar ac-2.1.6-SNAPSHOT-783f2.jar

> ...
> Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;
>         at es.ucm.fdi.ac.LogPanel.<init>(LogPanel.java:80)
>         at es.ucm.fdi.ac.Main.<init>(Main.java:85)
>         at es.ucm.fdi.ac.Main$2.run(Main.java:112)
> ...

**Comment by manuel-freire** [comment]
Fixed in latest versions
