### ISSUE TITLE
Error launching the similarity test

### ISSUE THREAD

**Issue by jsanta-upct** [manuel-freire/ac2#28]
Hello,

I was testing your software, but it crashed while launching the test (even using the default test (NCD). Executing the programa from the command line, it reports a NullPointerException. I attach a screenshot in case it helps.

![Captura de pantalla 2023-03-01 a las 13 43 51](https://user-images.githubusercontent.com/108326579/222142812-c494d172-6dc3-4cf7-a83a-1366964acb36.png)

UPDATE: I've checked that the error was caused by one of the source files imported, which is not a .py code file as the rest, but a notebook file.

**Comment by manuel-freire** [comment]
I have hopefully fixed this bug in the latest commits (in particular, see [this commit](https://github.com/manuel-freire/ac2/commit/30a9e6a178966904993bf86821f4355184dfa414#diff-b9f8d1b7d9a207e2d9ea6a52c81e13c3f3e5cbb4670c6cc4ff8565a976a9114cR102) ) - thanks for reporting!
