### ISSUE TITLE
Does the tool work for cross-language assignments?

### ISSUE THREAD

**Issue by euberdeveloper** [manuel-freire/ac2#30]
What if there are two or more codebases, one coded in java and one coded in Kotlin, with the second one basically "translating" the first codebase in a second language?

Would the tool work? In the documentation it's not clear

**Comment by manuel-freire** [comment]
Currently, the tool performs a check for "most popular language", and then uses the corresponding tokenizer for all files in each submission. I can point to where you can change this behavior, but it getting it to work well in a general case would not be easy (what about multi-language files, such as embedded JS in HTML?). A work-around is to use 2 runs of the tool, each on a different type of source-files. Kotlin is not currently supported, but there appears to be an available grammar in https://github.com/antlr/grammars-v4/tree/master/kotlin that could be easily added.

**Comment by euberdeveloper** [comment]
I think you didn't get the issue, what I'm talking about is that your tool does not support cross-language (also called multi-language) plagiarism detection
