### ISSUE TITLE
Documentation for ac2?

### ISSUE THREAD

**Issue by FreemanX** [manuel-freire/ac2#5]
Hi, I'd like to try out ac2 but the wiki page is empty.

**Comment by manuel-freire** [comment]
There are some papers that describe how AC works (linked in the readme.md), but there is no full manual that describes step-by-step operation. I will leave this issue open and build a wiki in the following weeks.

**Comment by manuel-freire** [comment]
Added a rough [quickstart](https://github.com/manuel-freire/ac2/wiki/Quickstart) guide.

**Comment by manuel-freire** [comment]
I feel that the quickstart guide is now complete enough to document basic usage. Please file further issues if you need additional documentation, describing what it is that you are trying to do.

**Comment by FreemanX** [comment]
Thank you very much!
